// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vblpqdxzibghojwegmlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibHBxZHh6aWJnaG9qd2VnbWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzY1NDgsImV4cCI6MjA1OTk1MjU0OH0.P1g2cPJSQMkKFQxM9mzBlx5jN8SJI4_WmlcbM1JK85o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);