name: Deploy React App to GitHub Pages

on:
  push:
    branches: ["main"]  # Run on pushes to main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js for React build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Make sure to use the version your app is built with

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build React app
      - name: Build React app
        run: npm run build

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload build artifacts to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'  # The folder where React's build output is stored

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
